# Site settings
title: 변기닷컴 Blog
header-img: img/home-bg.jpg
email: byungicom@gmail.com
copyright_name: byungicom
description: "생각을 배설하라"
baseurl: "https://sjs1178.github.io"
url: "https://sjs1178.github.io"
twitter_username: byungicom
github_username:  sjs1178
facebook_username:  byungicom
email_username:  byungicom@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
